// Mocks generated by Mockito 5.4.0 from annotations
// in client/test/role_tests/role_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:client/domain/role/role.dart' as _i2;
import 'package:client/domain/role/role_form.dart' as _i5;
import 'package:client/infrastructure/role/data_providers/role_api.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRole_0 extends _i1.SmartFake implements _i2.Role {
  _FakeRole_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RoleApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoleApi extends _i1.Mock implements _i3.RoleApi {
  MockRoleApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: '',
      ) as String);
  @override
  _i4.Future<_i2.Role> getRole(
    int? groupId,
    int? roleId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRole,
          [
            groupId,
            roleId,
            token,
          ],
        ),
        returnValue: _i4.Future<_i2.Role>.value(_FakeRole_0(
          this,
          Invocation.method(
            #getRole,
            [
              groupId,
              roleId,
              token,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Role>);
  @override
  _i4.Future<_i2.Role> createRole(
    int? groupId,
    _i5.RoleForm? role,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRole,
          [
            groupId,
            role,
            token,
          ],
        ),
        returnValue: _i4.Future<_i2.Role>.value(_FakeRole_0(
          this,
          Invocation.method(
            #createRole,
            [
              groupId,
              role,
              token,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Role>);
  @override
  _i4.Future<_i2.Role> updateRole(
    int? groupId,
    _i5.RoleForm? role,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRole,
          [
            groupId,
            role,
            token,
          ],
        ),
        returnValue: _i4.Future<_i2.Role>.value(_FakeRole_0(
          this,
          Invocation.method(
            #updateRole,
            [
              groupId,
              role,
              token,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Role>);
  @override
  _i4.Future<void> deleteRole(
    int? groupId,
    int? roleId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRole,
          [
            groupId,
            roleId,
            token,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
